services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "time_tracker"
      POSTGRES_USER: "neatly"
      POSTGRES_PASSWORD: "neatly"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/time_tracker"
      SPRING_DATASOURCE_USERNAME: "neatly"
      SPRING_DATASOURCE_PASSWORD: "neatly"
    depends_on:
      - db

volumes:
  db_data: