spring:
  datasource:
    url: ${datasource.url:jdbc:postgresql://db:5432/time_tracker}  # Использует имя сервиса db
    driver-class-name: org.postgresql.Driver
    username: ${datasource.username:neatly}
    password: ${datasource.password:neatly}
  flyway:
    locations: classpath:db/migration
    enabled: true

jwt:
  key: x7h3vE/AH1GFm8Ut88TrYQO8yK2P1+o0mLr4IN9z7r8=

server:
  port: 8080